spring.application.name=greenTravel
server.port=${PORT:8080}

# URL permitida para peticiones CORS (por defecto localhost)
cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}
# Habilitar la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Nombre fijo para la URL en memoria
spring.datasource.url=jdbc:h2:mem:greentraveldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect